In [8]:
import numpy as np

In [9]:
# buat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[25, 1, 5], [61, 0, 93],])
x

array([[25,  1,  5],
       [61,  0, 93]])

In [10]:
# tampilkan ukuran dari matrix x
x.shape

(2, 3)

In [11]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x[0:,]

array([[25,  1,  5],
       [61,  0, 93]])

In [12]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x[:,1]

array([1, 0])

In [13]:
import torch

In [14]:
# buat matrix X berukuran 2x3 menggunakan pytorch
x_pt = torch.tensor([[25, 15, 6], [1, 0, 93],])
x_pt

tensor([[25, 15,  6],
        [ 1,  0, 93]])

In [15]:
# tampilkan ukuran dari matrix x
x_pt.shape

torch.Size([2, 3])

In [16]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x_pt[0,:]

tensor([25, 15,  6])

In [17]:
# tampilkan seluruh elemen dari baris kedua dari matrix X

x_pt[:,1]

tensor([15,  0])

In [18]:
import tensorflow as tf

In [19]:
# buat matrix X berukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[25, 15, 66], [1, 0, 93],])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25, 15, 66],
       [ 1,  0, 93]], dtype=int32)>

In [20]:
# tampilkan ukuran dari matrix x
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [21]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x_tf[0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25, 15, 66], dtype=int32)>

In [22]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x_tf[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([15,  0], dtype=int32)>