In [13]:
import numpy as np

In [14]:
# buat vector x dengan ukuran 3x1
x = np.array([[93],
       [ 9],
       [ 3]])
x

array([[93],
       [ 9],
       [ 3]])

In [15]:
# hitung panjang vector x
len(x)

3

In [16]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [17]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [18]:
# akses elemen pertama dari vector x
x[0]

array([93])

In [19]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

In [20]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([[93,  9,  3]])

In [21]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [22]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[25],
       [ 2],
       [ 5]])
y

array([[25],
       [ 2],
       [ 5]])

In [23]:
# tampilkan ukuran dari vector x_t
y.shape

(3, 1)

In [24]:
import torch
import tensorflow as tf

In [30]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
x_pt = torch.tensor([[25],
       [ 0],
       [ 93]])
x_pt

tensor([[25],
        [ 0],
        [93]])

In [31]:
# lakukan transpose pada vector x dan simpan pada variabel x_pt.
x_pt = x_pt.T
x_pt

tensor([[25,  0, 93]])

In [32]:
# tampilkan ukuran dari vector x_t
x_pt.shape

torch.Size([1, 3])

In [33]:
# variabel y
y_pt = torch.tensor([[25],
       [ 15],
       [ 93]])
y_pt

tensor([[25],
        [15],
        [93]])

In [34]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_pt = y_pt.T
y_pt

tensor([[25, 15, 93]])